import { LanguageCode } from "@/lib/i18n";

const homepageChrome = {
  en: {
    editionLabel: "source-linked seed intelligence",
    compareOptions: "Compare options",
    browseMarkets: "Browse markets",
    searchRegulations: "Search regulations",
    mapWorkspace: "Explore the regulatory map",
    mapWorkspaceBody: "Use the map when you want to inspect tracked jurisdictions. For company-specific orientation, start with the assessment.",
    currentWorkspaceContext: "Current workspace context",
    matchingSeedRecords: "matching seed records",
    assessmentContextHint: "Use the assessment when entity facts, value-chain exposure or role-specific relevance are still unclear.",
    noMatchingRecords: "No matching regulation records for the current view. Clear filters or broaden the selected view.",
    openTablePreview: "Open scan-friendly table preview",
    records: "records",
    monitor: "Monitor",
    priority: "priority",
    priorityFirstReporting: "First reporting",
    prioritySourceLinks: "Source links",
    sourceToVerify: "Source to verify",
    sourceReviewNeeded: "source review needed",
    reviewDetails: "Review details"
  },
  es: {
    editionLabel: "inteligencia semilla con fuentes",
    compareOptions: "Comparar opciones",
    browseMarkets: "Ver mercados",
    searchRegulations: "Buscar regulaciones",
    mapWorkspace: "Explorar el mapa regulatorio",
    mapWorkspaceBody: "Use el mapa para inspeccionar jurisdicciones rastreadas. Para orientación específica de la empresa, empiece con la evaluación.",
    currentWorkspaceContext: "Contexto actual del espacio",
    matchingSeedRecords: "registros semilla coincidentes",
    assessmentContextHint: "Use la evaluación cuando los hechos de la entidad, la exposición de cadena de valor o la relevancia por rol aún no estén claros.",
    noMatchingRecords: "No hay registros regulatorios para la vista actual. Borre filtros o amplíe la vista seleccionada.",
    openTablePreview: "Abrir vista previa de tabla",
    records: "registros",
    monitor: "Monitorear",
    priority: "prioridad",
    priorityFirstReporting: "Primer reporte",
    prioritySourceLinks: "Enlaces de fuentes",
    sourceToVerify: "Fuente a verificar",
    sourceReviewNeeded: "revisión de fuente pendiente",
    reviewDetails: "Revisar detalles"
  },
  nl: {
    editionLabel: "brongekoppelde seed intelligence",
    compareOptions: "Opties vergelijken",
    browseMarkets: "Markten bekijken",
    searchRegulations: "Regelgeving zoeken",
    mapWorkspace: "De regelgevingskaart verkennen",
    mapWorkspaceBody: "Gebruik de kaart wanneer u gevolgde jurisdicties wilt inspecteren. Start voor bedrijfsspecifieke orientatie met de beoordeling.",
    currentWorkspaceContext: "Huidige werkruimtecontext",
    matchingSeedRecords: "overeenkomende seed-records",
    assessmentContextHint: "Gebruik de beoordeling wanneer entiteitsfeiten, waardeketenblootstelling of rolspecifieke relevantie nog onduidelijk zijn.",
    noMatchingRecords: "Geen regelgevingsrecords voor de huidige weergave. Wis filters of kies een bredere weergave.",
    openTablePreview: "Scanvriendelijke tabelpreview openen",
    records: "records",
    monitor: "Monitoren",
    priority: "prioriteit",
    priorityFirstReporting: "Eerste verslagjaar",
    prioritySourceLinks: "Bronlinks",
    sourceToVerify: "Bron om te verifieren",
    sourceReviewNeeded: "bronbeoordeling nodig",
    reviewDetails: "Details bekijken"
  },
  fr: {
    editionLabel: "donnees seed avec sources",
    compareOptions: "Comparer les options",
    browseMarkets: "Voir les marchés",
    searchRegulations: "Rechercher des règles",
    mapWorkspace: "Explorer la carte réglementaire",
    mapWorkspaceBody: "Utilisez la carte pour inspecter les juridictions suivies. Pour une orientation propre à l'entreprise, commencez par l'évaluation.",
    currentWorkspaceContext: "Contexte actuel",
    matchingSeedRecords: "fiches seed correspondantes",
    assessmentContextHint: "Utilisez l'evaluation lorsque les faits propres a l'entite, l'exposition de chaine de valeur ou la pertinence par role restent incertains.",
    noMatchingRecords: "Aucune fiche reglementaire ne correspond a la vue actuelle. Effacez les filtres ou elargissez la vue.",
    openTablePreview: "Ouvrir l'apercu de table",
    records: "fiches",
    monitor: "Surveiller",
    priority: "priorite",
    priorityFirstReporting: "Premier reporting",
    prioritySourceLinks: "Liens sources",
    sourceToVerify: "Source a verifier",
    sourceReviewNeeded: "revue de source requise",
    reviewDetails: "Voir les details"
  },
  de: {
    editionLabel: "quellenverlinkte Seed Intelligence",
    compareOptions: "Optionen vergleichen",
    browseMarkets: "Märkte ansehen",
    searchRegulations: "Regelungen suchen",
    mapWorkspace: "Regulierungskarte erkunden",
    mapWorkspaceBody: "Nutzen Sie die Karte, wenn Sie verfolgte Jurisdiktionen prüfen möchten. Für unternehmensspezifische Orientierung starten Sie mit der Bewertung.",
    currentWorkspaceContext: "Aktueller Arbeitskontext",
    matchingSeedRecords: "passende Seed-Datensaetze",
    assessmentContextHint: "Nutzen Sie die Bewertung, wenn Entitaetsfakten, Wertschoepfungsketten-Exponierung oder rollenspezifische Relevanz noch unklar sind.",
    noMatchingRecords: "Keine Regulierungsdatensaetze fuer die aktuelle Ansicht. Filter loeschen oder Ansicht erweitern.",
    openTablePreview: "Scanfreundliche Tabellenvorschau oeffnen",
    records: "Datensaetze",
    monitor: "Beobachten",
    priority: "Prioritaet",
    priorityFirstReporting: "Erste Berichterstattung",
    prioritySourceLinks: "Quellenlinks",
    sourceToVerify: "Quelle zu pruefen",
    sourceReviewNeeded: "Quellenpruefung erforderlich",
    reviewDetails: "Details pruefen"
  },
  pt: {
    editionLabel: "seed intelligence com fontes",
    compareOptions: "Comparar opções",
    browseMarkets: "Ver mercados",
    searchRegulations: "Pesquisar regulações",
    mapWorkspace: "Explorar o mapa regulatório",
    mapWorkspaceBody: "Use o mapa quando quiser inspecionar jurisdições acompanhadas. Para orientação específica da empresa, comece pela avaliação.",
    currentWorkspaceContext: "Contexto atual",
    matchingSeedRecords: "registros seed correspondentes",
    assessmentContextHint: "Use a avaliação quando fatos da entidade, exposição na cadeia de valor ou relevância por função ainda não estiverem claros.",
    noMatchingRecords: "Nenhum registro regulatório corresponde à visão atual. Limpe filtros ou amplie a visão selecionada.",
    openTablePreview: "Abrir prévia de tabela",
    records: "registros",
    monitor: "Monitorar",
    priority: "prioridade",
    priorityFirstReporting: "Primeiro reporte",
    prioritySourceLinks: "Links de fontes",
    sourceToVerify: "Fonte a verificar",
    sourceReviewNeeded: "revisão de fonte necessária",
    reviewDetails: "Revisar detalhes"
  }
} satisfies Record<LanguageCode, Record<string, string>>;

export type HomepageChromeKey = keyof typeof homepageChrome.en;

export function getHomepageChrome(language: LanguageCode, key: HomepageChromeKey) {
  return homepageChrome[language]?.[key] || homepageChrome.en[key];
}
